# Generated by Django 4.2.3 on 2023-07-11 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_service', '0002_remove_employee_ff_alter_employee_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 19, 34, 30, 807856, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
