# Generated by Django 4.2.3 on 2023-07-12 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_service', '0003_alter_employee_dob_alter_employee_doj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='ff',
            field=models.CharField(default=datetime.datetime(2023, 7, 12, 17, 14, 2, 620325, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='eId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
