# Generated by Django 4.2.3 on 2023-07-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_service', '0004_remove_employee_id_employee_ff_alter_employee_eid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ff',
            new_name='ffood',
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateTimeField(null=True),
        ),
    ]
