# Generated by Django 4.2.3 on 2023-07-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_service', '0005_rename_ff_employee_ffood_alter_employee_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ffood',
            new_name='ff',
        ),
    ]
