# Generated by Django 4.2.3 on 2023-07-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_service', '0006_rename_ffood_employee_ff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fp',
        ),
    ]
