# Generated by Django 4.2.3 on 2023-07-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data_service', '0007_remove_employee_fp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
